const STATIC='nigun-shell-v29-modern-games';
const OFFLINE_MEDIA='nigun-user-media-v1';
const SETTINGS='nigun-settings-v1';
const GAME_DB='nigun-modern-games-v1', GAME_DB_VER=1, GAME_FILES='files';
const CORE=['./','index.html','manifest.webmanifest','icon-192.png','icon-512.png','apple-touch-icon.png'];
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(STATIC);for(const x of CORE){try{await c.add(x)}catch(_){}}await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys()){if(k.startsWith('nigun-shell-')&&k!==STATIC)await caches.delete(k)}await self.clients.claim()})()));
function gameDB(){return new Promise((ok,fail)=>{const r=indexedDB.open(GAME_DB,GAME_DB_VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(GAME_FILES))d.createObjectStore(GAME_FILES,{keyPath:'path'});if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta',{keyPath:'slug'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})}
async function gameFile(path){try{const d=await gameDB();return await new Promise((ok,fail)=>{const tx=d.transaction(GAME_FILES,'readonly'),r=tx.objectStore(GAME_FILES).get(path);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>fail(r.error)})}catch(_){return null}}
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin===self.location.origin&&u.pathname.includes('/__nigun_games__/')){e.respondWith((async()=>{const f=await gameFile(u.pathname);if(!f)return new Response('Game file is not installed',{status:404,headers:{'content-type':'text/plain;charset=utf-8'}});return new Response(f.blob,{status:200,headers:{'content-type':f.type||'application/octet-stream','cache-control':'no-store','access-control-allow-origin':'*'}})})());return}const isPage=r.mode==='navigate'||u.pathname.endsWith('/index.html');if(isPage){e.respondWith((async()=>{try{const res=await fetch(r,{cache:'no-store'});if(res&&res.ok)(await caches.open(STATIC)).put('index.html',res.clone()).catch(()=>{});return res}catch(_){return(await caches.match('index.html'))||(await caches.match('./'))}})());return}e.respondWith((async()=>{const hit=await caches.match(r);if(hit)return hit;try{const res=await fetch(r);if(res&&res.ok)(await caches.open(STATIC)).put(r,res.clone()).catch(()=>{});return res}catch(err){throw err}})())});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws){if('focus'in w)return w.focus()}return clients.openWindow('./')}))});
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch(_){d={body:e.data?.text?.()||''}}e.waitUntil(self.registration.showNotification(d.title||'Nigun',{body:d.body||'יש עדכון חדש בניגון',icon:'icon-192.png',badge:'icon-192.png',tag:d.tag||'nigun-push',data:d.data||{}}))});
async function saveWeekly(p){const c=await caches.open(SETTINGS);await c.put(new Request(new URL('__weekly_summary__',self.location).href),new Response(JSON.stringify(p),{headers:{'content-type':'application/json'}}))}
async function readWeekly(){const c=await caches.open(SETTINGS),r=await c.match(new Request(new URL('__weekly_summary__',self.location).href));return r?await r.json():null}
self.addEventListener('message',e=>{if(e.data?.type==='SAVE_WEEKLY_SUMMARY')e.waitUntil(saveWeekly(e.data.payload))});
self.addEventListener('periodicsync',e=>{if(e.tag!=='nigun-weekly-summary')return;e.waitUntil((async()=>{const p=await readWeekly();if(!p||Date.now()<(p.next||0))return;await self.registration.showNotification(p.title||'סיכום ההאזנה השבועי שלך',{body:p.body||'פתח את Nigun לצפייה בסיכום',icon:'icon-192.png',badge:'icon-192.png',tag:'nigun-weekly'});p.next=Date.now()+7*86400000;await saveWeekly(p)})())});