const STATIC='nigun-offline-v20-games-center';
const OFFLINE_MEDIA='nigun-user-media-v1';
const SETTINGS='nigun-settings-v1';
const CORE=['./','index.html','manifest.webmanifest','icon-192.png','icon-512.png','apple-touch-icon.png'];
self.addEventListener('install',e=>e.waitUntil(caches.open(STATIC).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys()){if(k.startsWith('nigun-shell-')&&k!==STATIC)await caches.delete(k)}await self.clients.claim()})()));
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const isPage=r.mode==='navigate'||new URL(r.url).pathname.endsWith('/index.html');if(isPage){e.respondWith((async()=>{try{const res=await fetch(r,{cache:'no-store'});if(res&&res.ok)(await caches.open(STATIC)).put('index.html',res.clone()).catch(()=>{});return res}catch(_){return(await caches.match('index.html'))||(await caches.match('./'))}})());return}e.respondWith((async()=>{const hit=await caches.match(r);if(hit)return hit;try{const res=await fetch(r);if(res&&res.ok)(await caches.open(STATIC)).put(r,res.clone()).catch(()=>{});return res}catch(err){throw err}})())});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws){if('focus'in w)return w.focus()}return clients.openWindow('./')}))});
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch(_){d={body:e.data?.text?.()||''}}e.waitUntil(self.registration.showNotification(d.title||'Nigun',{body:d.body||'יש עדכון חדש בניגון',icon:'icon-192.png',badge:'icon-192.png',tag:d.tag||'nigun-push',data:d.data||{}}))});
async function saveWeekly(p){const c=await caches.open(SETTINGS);await c.put(new Request(new URL('__weekly_summary__',self.location).href),new Response(JSON.stringify(p),{headers:{'content-type':'application/json'}}))}
async function readWeekly(){const c=await caches.open(SETTINGS),r=await c.match(new Request(new URL('__weekly_summary__',self.location).href));return r?await r.json():null}
self.addEventListener('message',e=>{if(e.data?.type==='SAVE_WEEKLY_SUMMARY')e.waitUntil(saveWeekly(e.data.payload))});
self.addEventListener('periodicsync',e=>{if(e.tag!=='nigun-weekly-summary')return;e.waitUntil((async()=>{const p=await readWeekly();if(!p||Date.now()<(p.next||0))return;await self.registration.showNotification(p.title||'סיכום ההאזנה השבועי שלך',{body:p.body||'פתח את Nigun לצפייה בסיכום',icon:'icon-192.png',badge:'icon-192.png',tag:'nigun-weekly'});p.next=Date.now()+7*86400000;await saveWeekly(p)})())});
